spring:
  application:
    name: payment-service
  jackson:
    default-property-inclusion: non_null
  cloud:
    compatibility-verifier:
      enabled: true
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 5000
            loggerLevel: basic
          order-service:
            url: http://${minimart.services.order.host:order-service}:${minimart.services.order.port:8083}
  datasource:
    url: jdbc:mysql://${DB_HOST:host.docker.internal}:${DB_PORT:3306}/minimart_payment?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ${DB_USERNAME:minimart}
    password: ${DB_PASSWORD:minimart}

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when_authorized

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{correlationId:-}]"

minimart:
  services:
    order:
      host: order-service
      port: 8083
